# Generated by Django 4.2.9 on 2025-09-30 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientprofile',
            old_name='blood_type',
            new_name='blood_group',
        ),
        migrations.RenameField(
            model_name='patientprofile',
            old_name='emergency_contact_relationship',
            new_name='policy_number',
        ),
        migrations.RenameField(
            model_name='patientprofile',
            old_name='insurance_policy_number',
            new_name='relationship',
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='patient_status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('discharged', 'Discharged')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='zip_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
