# Generated by Django 4.2.9 on 2025-09-30 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_rename_blood_type_patientprofile_blood_group_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientprofile',
            name='patient_status',
        ),
    ]
