# Generated by Django 4.2.9 on 2025-09-30 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_remove_patient_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Prescription',
        ),
    ]
